import { useState, useEffect } from "react";
import "./viewReports.css";

export default function ViewReports() {
  const [reports, setReports] = useState([]);
  const [requestedReports, setRequestedReports] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    // Pre-generated reports available from Admin
    const initialReports = [
      {
        id: 1,
        title: "Vehicle Maintenance - Monthly",
        type: "Maintenance",
        date: "2026-02-01",
        summary: "Monthly maintenance summary of all vehicles.",
        available: true,
      },
      {
        id: 2,
        title: "Driver Performance Report",
        type: "Performance",
        date: "2026-02-01",
        summary: "Driver punctuality, trips completed, complaints resolved.",
        available: true,
      },
    ];
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setReports(initialReports);
  }, []);

  // Search reports
  const filteredReports = reports.filter(
    (r) =>
      r.title.toLowerCase().includes(search.toLowerCase()) ||
      r.type.toLowerCase().includes(search.toLowerCase())
  );

  // Request a new report
  const requestReport = (reportTitle) => {
    const alreadyRequested = requestedReports.find((r) => r.title === reportTitle);
    if (alreadyRequested) {
      alert(`Report "${reportTitle}" is already requested`);
      return;
    }
    const newRequest = {
      id: requestedReports.length + 1,
      title: reportTitle,
      status: "Pending",
    };
    setRequestedReports((prev) => [...prev, newRequest]);
    alert(`Report request "${reportTitle}" submitted to Admin`);
  };

  // Simulate Admin generating requested report after 5 seconds
  useEffect(() => {
    const timer = setTimeout(() => {
      if (requestedReports.length > 0) {
        const completedReports = requestedReports.map((r) => ({
          id: reports.length + r.id,
          title: r.title,
          type: "Custom",
          date: new Date().toISOString().slice(0, 10),
          summary: "Report generated by Admin.",
          available: true,
        }));
        setReports((prev) => [...prev, ...completedReports]);
        setRequestedReports([]);
        alert("Admin has generated your requested reports!");
      }
    }, 5000);

    return () => clearTimeout(timer);
  }, [requestedReports, reports]);

  return (
    <div className="reports-page">
      <h1>Admin Reports</h1>
      <p>View pre-generated reports or request new ones.</p>

      {/* Search Bar */}
      <div className="report-search-wrapper">
        <input
          type="text"
          placeholder="Search by title or type..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="report-search"
        />
      </div>

      {/* Request new report */}
      <div className="request-report">
        <h3>Request a New Report</h3>
        <button onClick={() => requestReport("Complaint Resolution Statistics")}>
          Request Complaint Resolution Report
        </button>
      </div>

      {/* Available Reports */}
      <div className="report-list">
        {filteredReports.map((r) => (
          <div className="report-card" key={r.id}>
            <div className="report-header">
              <strong>{r.title}</strong> | <em>{r.type}</em>
            </div>
            <p>{r.summary}</p>
            <small>Date: {r.date}</small>
            <div className="report-actions">
              {r.available ? (
                <button onClick={() => alert(`Downloading ${r.title}`)}>
                  Download / View
                </button>
              ) : (
                <span>Pending Admin Generation</span>
              )}
            </div>
          </div>
        ))}
        {filteredReports.length === 0 && <p className="no-reports">No reports found.</p>}
      </div>

      {/* Pending Requests */}
      {requestedReports.length > 0 && (
        <div className="pending-requests">
          <h3>Pending Report Requests</h3>
          {requestedReports.map((r) => (
            <div key={r.id}>
              {r.title} - Status: {r.status}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}